version: 0.0
os: linux
files:
  - source: /target/API-0.0.1
    destination: //opt/tomcat/webapps/hl7v2API
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
